### ISSUE TITLE
vaadin 8 support

### ISSUE THREAD

**Issue by bsutton** [TatuLund/GridFastNavigation#16]
Whats the chance of getting vaadin 8 support for this add on?

**Comment by TatuLund** [comment]
This is in my plans after I am confident that Vaadin 7 version has sufficient functionality, which is starting to be close.

**Comment by bsutton** [comment]
So as I need vaadin 8 support for a project I've gone ahead and ported the code.
Looks like the port works give or take a few bugs (which  I think may be also be in the v7 version - will report separately).

If created a pull request would you accept it?
Any particular requirements?
I've tried to use (what I think are) best practices for vaadin 8 grids. So a few changes as I'ved used binders and listdataproviders with appropriate pojos for each data source (the message area is now a grid).

**Comment by bsutton** [comment]
Also I wasn't certain what VFilterSelect was used for and its not supported in vaadin 8 so I've commented out related code at this point.

**Comment by TatuLund** [comment]
Thanks for your interested, I am flattered.

"So as I need vaadin 8 support for a project I've gone ahead and ported the code."

That sounds promising. My understanding is that changes needed are minor. There has not been big changes in Grid client side. 

"If created a pull request would you accept it? Any particular requirements?"

Yes, I would like to use it as baseline atleast. I will release version 2.x series for Vaadin 8 and put it to different branch so that two versions can be maintained in parallel. That is how we have done it with other add-ons as well.

Also I would like to package current add-on as v7 compatibility add-on in Vaadin 8 version. I can do that.

"Also I wasn't certain what VFilterSelect was used for and its not supported in vaadin 8 so I've commented out related code at this point."

VFilterSelect is the internal widget name for ComboBox client side. In Vaadin 8 it has been renamed to VComboBox. I just checked some details, and I think it should be as straightforwad as just renaming classname.

Some changes may be needed to deal with changes of DateField. The VPopupCalendar in Vaadin 8 handles only date input, and VPopupTimeCalendar is used for Date+Time input. 

What is missing in current add-on is support for VListSelect widget. 

"Looks like the port works give or take a few bugs (which  I think may be also be in the v7 version - will report separately)."

That would be highly appreciated.

**Comment by TatuLund** [comment]
Version 2.0.0 is now released.
