### ISSUE TITLE
SelectionListener on Grid not working after using FastNavigation

### ISSUE THREAD

**Issue by dangerground** [TatuLund/GridFastNavigation#42]
Hi,
if using this extension I no longer can use the itemClickListener or selectionListener from the Grid object. My application needs to know the currently selected row to be able to switch to an edit mode in which the FastNavigation is used to edit the dataset (the default vaadin behaviour using a doubleclick is driving me nuts).

So it would be nice to still have the selection event available, I also can work with an method implemented in FastNavigation itself.

using Vaadin 8.2.1 and FastNavigation 2.1.9

**Comment by TatuLund** [comment]
When using FastNavigation, you can set it to open editor with single click with setOpenEditorWithSingleClick(boolean enable) method. Actually I have made it default. So if the sole purpose for listening for selection event is to have editor to open with single click, you do not need that. 

But thanks for info. I think there is some stopEventPropagation() (which do have some purpose) in FastNavigation that probably interferes Grid normal events. I need to investigate it a bit more, if it can be avoided.

**Comment by TatuLund** [comment]
I spent some time to investigate this issue. It is not a bug, but rather bad documentation. I added some notes to setOpenEditorWithSingleClick(..) JavaDoc for clarification.

It is the opening Editor that captures the click, this if setOpenEditorWithSingleClick(true) is used Grid's item click event will not fire and selection event fires only with shift + space (not on mouse click)

There are two alternatives. You can use setOpenEditorWithSingleClick(false), when those work normally. Or if you want to use setOpenEditorWithSingleClick(true), you can use RowFocusListener or CellFocusListener of the add-on instead of Grid's item click listener.
