### ISSUE TITLE
Quit edit mode, when clicking on selection check box

### ISSUE THREAD

**Issue by apgsga-stb** [TatuLund/GridFastNavigation#60]
In a Grid with multi select set on you get this selection checkboxes on the left. But if you're in edit mode, you can't select an row anymore, you have to quit edit mode first.

What do you think about quitting edit mode automatically, when clicking on a selection check box? Like when clicking outside the grid.

**Comment by TatuLund** [comment]
Which framework version you are using?

**Comment by TatuLund** [comment]
This is really weird. The selection is toggled if you click multiselection check box column outside the checkbox, but not by clicking inside.

**Comment by apgsga-stb** [comment]
We're using Vaadin 8.2.0.

**Comment by TatuLund** [comment]
Ok. I was testing with Vaadin 8.3.3. Do you have same symptoms as I have? Do you also see ellipsis i.e. "..." before checkbox on editor row?

**Comment by apgsga-stb** [comment]
Yes, I observe the very same behaviour.

**Comment by TatuLund** [comment]
I have discussed this with Vaadin framework development. I think this should be addressed in framework instead of the add-on.

**Comment by apgsga-stb** [comment]
Do I have to open an issue for the framework or will it be addressed without my intervention?

**Comment by AlexByte** [comment]
Can you provide screenshot with selection checkboxes?

**Comment by TatuLund** [comment]
At the moment Grid has been implemented so, that if Editor is open, MultiSelectionModel will disable the CheckBoxes (except the one that is on Editor row itself). There are two bugs in Grid, 1. the cells take the click event and change MultiSelectionModel state, 2. there is ellipsis on Editor row, which should not be there. 

However we have had some discussion, that CheckBoxes possibly should be actually enabled when  Grid is in unbuffered editor mode. Unbuffered editor mode was added later, and the original idea of integrated Editor was to have it sort of "modal". So another interpreation is that 1. is not actually a bug, but the bug is that CheckBoxes should be enabled. Altering this part of the implementation in framework code would be trivial.

**Comment by TatuLund** [comment]
@apgsga-stb I spotted a bug in FastNavigation when using multiselection model, see #65 Have you noticed the same?

**Comment by apgsga-stb** [comment]
No, not really. Here, column enabling and disabling works correctly. And the events are reporting the correct columns.

**Comment by TatuLund** [comment]
@apgsga-stb @AlexByte have you tested this with Framework 8.5.0?
