### ISSUE TITLE
<ESC>-Click freezes editor (or even more)

### ISSUE THREAD

**Issue by apgsga-stb** [TatuLund/GridFastNavigation#67]
If you click on a row with ESC key pressed, the grid freezes. 

Running sample:
```java
public class FastNavigationUI extends UI {
	@Override
	protected void init(VaadinRequest request) {
		Grid<Todo> grid = new Grid<>();
		grid.setItems(new Todo("One"), new Todo("Two"));
		grid.setHeightByRows(3);
		
		new FastNavigation<>(grid, false, true);

		ComboBox<String> typeField = new ComboBox<>();
		typeField.setItems("One one one one one",
				"Two two two two two two", 
				"Three three three three three three three three", 
				"Four four four four four", 
				"More (outside table area)");
		grid.addColumn(Todo::getType).setEditorComponent(typeField, Todo::setType).setExpandRatio(1);

		grid.getEditor().setEnabled(true);
		grid.getEditor().setBuffered(false);
		setContent(grid);
	}

	private static class Todo {
		private String type;

		public Todo(String type) {
			this.type = type;
		}

		public String getType() {
			return type;
		}

		public void setType(String type) {
			this.type = type;
		}
	}
}

```

**Comment by TatuLund** [comment]
Yes, I can easily replicate this issue.

**Comment by TatuLund** [comment]
I also noticed, that if you navigate with keyboard, it will work. It is just blocking editor opening by mouse click once. After keyboard navigation operation returns to normal.

**Comment by TatuLund** [comment]
The add-on does not have special treatment for ESC key. I tried to replicate this also with Grid without add-on, since I had difficulties to figure out why this happens.

In Vaadin 8.4+ you can open Grid with single click with this method

```
		grid.addItemClickListener(event -> {
			grid.getEditor().editRow(event.getRowIndex());
		});
```

I noticed that there is somewhat odd behavior as well when I hold ESC and click row. Some times I see the progress indicator there getting stuck, etc. Editor is not opened (ESC is probably caught and editor closed immediately). I think there is some inconsistency in state after that, but operation returns normal quickly.

When I enable FastNavigation with above code (and naturally single click opening in add-on disabled), Holding ESC and click row. Same as above, editor opening is not working for a while, but operation returns normal.

I think the root cause is not actually in the add-on, but somewhere in Grid code. There seems to be odd behavior both with add-on and without it.

**Comment by TatuLund** [comment]
But further debuging and testing revealed that reason for odd behavior with Grid without add-on and with add-on was different, I could find a fix for FastNavigation.
