### ISSUE TITLE
Grid editor Columns get misaligned

### ISSUE THREAD

**Issue by zsuzsannakokai** [TatuLund/GridFastNavigation#78]
Vaadin Version: both 8.5.1 and 8.5.2
Editor mode: unbuffered
FastNavigationAddon Version: 2.3.9

Adding a new item to the Grid, with setting focus on a cell that is at the end of the Grid:
Calling fastNavigation.setFocusedCell
![clipboard02](https://user-images.githubusercontent.com/43134934/46875169-46bd3f00-ce3b-11e8-9042-bb440e1f01f6.jpg)
Note: 
- Browser is not resized during the time
- Grid: sizeFull, with horizontal scrollbar, lots of columns

Maybe it has something with this issue:
https://github.com/vaadin/framework/issues/7276
Tatu: "There is proper fix in GridFastNavigation add-on version 2.3.5 (however it is usable only in un-buffered mode), I am also considering adding simple extension to add-on that can be used with buffered editor as well."
What is the "proper fix" for it?

**Comment by TatuLund** [comment]
In GridFastNavigation there is fix to Grid Editor bug: "Editor columns are not resized according to resized Grid columns". There are also two more fixes (hidden columns not being treated properly and Editor was not resized when Browser was resized and Grid was set full width). However there seems to be fourth bug, that Editor columns are sometimes misaligned when Editor is opened. There is not fix for that. Note, we fixed another issue in Vaadin 7, which is somewhat similar, but is not the same case (see: https://github.com/vaadin/framework/pull/11092 )

**Comment by zsuzsannakokai** [comment]
"However there seems to be fourth bug"
You are likely right, because columns were not resized during the time

**Comment by TatuLund** [comment]
After some play I found at least one Grid bug, which causes artifact you see with the demo app of the FastNavigation. As you see, when it starts there is five rows. When you add more rows, so that scroll bars appears. Also horizontal scroll bar will appear, since the vertical one takes some space and columns do not fit. When you click to open the editor, Grid's internal column resizing is triggered, but the new column sizes are not applied to editor. Hence some Editor column's will be narrower (the misalignment is the same amount as vertical scroll bar width). I think it could be fixable via Grid's internal logic, but not patchable via FastNavigation extension.

**Comment by zsuzsannakokai** [comment]
Hi Tatu,

Thank you for your effort.

When I understand it well, you could reproduce 100% the bug above. 
"the misalignment is the same amount as vertical scroll bar width" -> don't you mean horizontal scrollbar? On the picture above it seems to be completely the same.
"I think it could be fixable via Grid's internal logic" -> is it planned to be fixed somehow?

Best regards,
Zsuzsa

**Comment by TatuLund** [comment]
There is workaround for this issue. You can call grid.recalculateColumnWidths() when adding new rows to Grid.
