### ISSUE TITLE
EditorOpenListener is not called when opening Editor programmatically

### ISSUE THREAD

**Issue by zsuzsannakokai** [TatuLund/GridFastNavigation#80]
Vaadin Version: 8.5.2
FastNavigation Version: 2.3.9

EditorOpenListener is called well by opening the editor, but not in the case when it is a new item in the Grid.

**Comment by TatuLund** [comment]
Thanks for reporting this. I did some testing. It seems that EditorOpenEvent is not fired when editor is opened programmatically.

**Comment by TatuLund** [comment]
I did quite extensive research of the logic how Grid works. There is no easy way to implement this in FastNavigation. The programmatic opening of the Editor is not feasible to detect in client side. There is also Editor open event in Grid itself, which is triggered also when Editor is opened programmatically. There is problem there too, since it is fully server side implementation, it does not have method isUserOriginated() to distinguish whether Editor was opened by user or editRow() call.

**Comment by TatuLund** [comment]
Addressed by editRow(row,col) method introduced in https://github.com/TatuLund/GridFastNavigation/commit/b8feb447459c5b535e2d316d23ace74e0f450d43
